default:
  plugins:
    - image
    - link

alternate:
  selector: textarea.table-editor
  toolbar: styleselect | bold italic | media image | undo redo | table
  plugins:
    - table
    - media